name: Feature request
description: Suggest a feature we can add to theme/module
labels: ["enhancement"]
body:
  - type: dropdown
    id: resource
    attributes:
      label: Resource
      description: What resource is this issue about?
      options:
        - Billing
        - Unix
        - Carbon
        - Socialite
    validations:
      required: true

  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
